config/routes.rb
Denemearena::Application.routes.draw do

  resources :debts

 resources :authentications
 resources :friends
 resources :posts
 resources :mails

  
   get '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
  controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
 
  
  root to: 'authentications#home'
  
  get '/contact' , :to => 'pages#contact'
  get '/about' , :to => 'pages#about'
  get '/help' , :to =>'pages#help'
 

  

end

app/models/debt.rb
class Debt < ActiveRecord::Base
attr_accessible :amount, :expirity, :friend_id, :type, :user_id, :status  
  
  validates :amount, :numericality => { :greater_than_or_equal_to => 0}, :presence => true
  validates :friend_id, :presence => true
  validates :expirity, :presence => true
  
 D_TYPES = [['Borrow', '1'], ['Lend', '2']]
 D_STATS = [['Outstanding', '0'], ['Paid', '1']]
  

  
  
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_action :set_debt, only: [:show, :edit, :update, :destroy]
 before_filter :authenticate_user!
  # GET /debts
  # GET /debts.json
  def index
    if params[:status]
      status = params[:status]
    else
      status = 0
    end
    @debts = current_user.debts.where(:status => status)
    # @debts = Debt.all
  end

  # GET /debts/1
  # GET /debts/1.json
  def show
    @debt=Debt.find(params[:id])
    
  end

  # GET /debts/new
  def new
    @debt = Debt.new
    @debt.friend_id = params[:friend_id]
    @debt.type = params[:type]
    @debt.status = params[:status]
  end

  # GET /debts/1/edit
  def edit
    @debt = Debt.find(params[:id])
  end

  # POST /debts
  # POST /debts.json
  def create
    @debt = current_user.debts.build(params[:debt])

    respond_to do |format|
      if @debt.save
        format.html { redirect_to @debt, notice: 'Debt was successfully created.' }
        format.json { render action: 'show', status: :created, location: @debt }
      else
        format.html { render action: 'new' }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debts/1
  # PATCH/PUT /debts/1.json
  def update
    @debt = Debt.find(params[:id])
    respond_to do |format|
      if @debt.update(debt_params)
        format.html { redirect_to @debt, notice: 'Debt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1
  # DELETE /debts/1.json
  def destroy
    @debt = Debt.find(params[:id])
    @debt.destroy
    respond_to do |format|
      format.html { redirect_to debts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debt_params
      params.require(:debt).permit(:friend_id, :amount, :type, :expirity, :status)
    end
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/views/debts/_form.html.erb
<%= form_for(@debt) do |f| %>
  <% if @debt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debt.errors.count, "error") %> prohibited this debt from being saved:</h2>

      <ul>
      <% @debt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :friend_id %><br>
   <%= f.collection_select(:friend_id, current_user.friends, :id, :name, {:prompt => true})%>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
  
  </div>
  <div class="field">
    <%= f.label :expirity %><br>
    <%= f.date_select :expirity %>
  </div>
  <div class="field">
 <%= f.hidden_field :status, :value => 0 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debts/edit.html.erb
<%= render 'shared/form' %>
<h1>Editing debt</h1>

<%= render 'form' %>

<%= link_to 'Show', @debt %> |
<%= link_to 'Back', debts_path %>

app/views/debts/index.html.erb
<%= render 'shared/form' %>

<h1>Listing debts</h1>

<table>
  <thead>
    <tr>
      <th>Friend</th>
      <th>Amount</th>
      <th>Expirity</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @debts.each do |debt| %>
      <tr>
        <td><%= Friend.find(debt.friend_id).name %></td>
        <td><%= debt.amount %></td>
      
        <td><%= debt.expirity %></td>
        <td><%= debt.status %></td>
        <td><%= link_to 'Show', debt %></td>
        <td><%= link_to 'Edit', edit_debt_path(debt) %></td>
        <td><%= link_to 'Destroy', debt, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
	
		
  </tbody>
</table>

<br>

<%= link_to 'New Debt', new_debt_path %>

app/views/debts/new.html.erb
<%= render 'shared/form' %>
<h1>New debt</h1>

<%= render 'form' %>

<%= link_to 'Back', debts_path %>

app/views/debts/show.html.erb
<%= render 'shared/form' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Friend:</strong>
  <%= Friend.find(@debt.friend_id).name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @debt.amount %>
</p>

<p>
  
</p>

<p>
  <strong>Expirity:</strong>
  <%= @debt.expirity %>
</p>

<p>
  <strong>Status:</strong>
  <%= @debt.status %>
</p>

<%= link_to 'Edit', edit_debt_path(@debt) %> |
<%= link_to 'Back', debts_path %>