config/routes.rb
Denemearena::Application.routes.draw do

  resources :debts

 resources :authentications
 resources :friends
 resources :posts
 resources :mails

  
   get '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
  controllers: {omniauth_callbacks: "authentications", registrations: "registrations"}
 
  
  root to: 'authentications#home'
  
  get '/contact' , :to => 'pages#contact'
  get '/about' , :to => 'pages#about'
  get '/help' , :to =>'pages#help'
 

  

end

app/views/shared/_form.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
	    <div class="container">
          <h6> BORÇ TAKİP</h6>
           <nav>
  			 	<ul class="nav pull-right">
     			
    			  <li><%= link_to "Help", help_path %></li>
				  <% if user_signed_in? %>
				  <% else %>
				 <li> <%= link_to "Login", new_user_session_path %></li>
				  <% end %>
   		   		</ul>
 		   </nav>
	   </div>
	   </div>
</header>

<body>

<% if user_signed_in? %>
 Logged in as <strong><%= current_user.email %></strong>.
 <%= link_to 'Home' , debts_path  %> |
 <%= link_to 'Edit profile', edit_user_registration_path %> |
 <%= link_to 'Authentications', authentications_path %> |
  <%= link_to 'Debts', debts_path %> |
 <%= link_to "Friends", friends_path %> |
 <%= link_to "Logout", destroy_user_session_path, method: :delete %>
   <%= render 'shared/user_info' %>
<% else %>

<div class="center hero-unit">
	 <h1>BORÇ TAKİP SİTESİNE HOŞGELDİNİZ</h1></br>
	 <h3>Siteye Giriş yaparak borçlarınızı takip etmeye hemen başlayabilirsiniz.</h3></br>
	 
   <%= link_to "Sign up", new_user_registration_path %> |
   <%= link_to "Login", new_user_session_path %>
 
 <li><%= link_to "Facebook", user_omniauth_authorize_path(:facebook) %></li>
 <li><%= link_to "Twitter", user_omniauth_authorize_path(:twitter) %></li>
<% end %>



 <div class="center hero-unit">
 </body>
	 <footer class="footer">
  
	   <nav>
	     <ul>
	 	   <li><%= link_to "Contact",    contact_path %></li>
	 	  <li><%= link_to "About",    about_path %></li></br>
      
	     </ul>
	   </nav>
	 </footer>
	 